import { ResourceDef } from "./types";
export const RESOURCES: ResourceDef[] = [
{id:"iron_ore",name:"Eisenerz",category:"raw",description:"Grundrohstoff für Eisenverarbeitung."},{id:"copper_ore",name:"Kupfererz",category:"raw",description:"Rohstoff für Leitermaterialien."},{id:"coal",name:"Kohle",category:"raw",description:"Brennstoff und Prozessmaterial."},{id:"stone",name:"Stein",category:"raw",description:"Mineralischer Baustoff."},{id:"silicon_ore",name:"Siliziumerz",category:"raw",description:"Erz für fortgeschrittene Elektronik."},
{id:"iron_ingot",name:"Eisenbarren",category:"material",description:"Geschmolzenes Eisen."},{id:"copper_ingot",name:"Kupferbarren",category:"material",description:"Geschmolzenes Kupfer."},{id:"coke",name:"Koks",category:"material",description:"Veredelter Kohlenstoff."},{id:"graphite",name:"Graphit",category:"material",description:"Leitfähiges Kohlenstoffmaterial."},{id:"stone_brick",name:"Steinziegel",category:"material",description:"Verdichteter Steinbaustoff."},{id:"glass",name:"Glas",category:"material",description:"Veredeltes Silikatmaterial."},{id:"iron_plate",name:"Eisenplatte",category:"material",description:"Weiterverarbeitete Eisenkomponente."},{id:"copper_wire",name:"Kupferdraht",category:"material",description:"Leitmaterial für Stromkreise."},{id:"gear",name:"Zahnrad",category:"material",description:"Mechanische Basiskomponente."},{id:"composite_plate",name:"Verbundplatte",category:"material",description:"Belastbare Mehrschichtplatte."},{id:"coil",name:"Spule",category:"material",description:"Gewickelte Leiterkomponente."},{id:"silicon_ingot",name:"Siliziumbarren",category:"material",description:"Reines Silizium für Wafer."},{id:"silicon_wafer",name:"Siliziumwafer",category:"material",description:"Trägermaterial für Chips."},{id:"logic_chip",name:"Logikchip",category:"material",description:"Basiselektronik für Steuerungen."},{id:"ceramic_plate",name:"Keramikplatte",category:"material",description:"Hitzebeständige Keramikkomponente."},
{id:"forming_tool",name:"Formwerkzeug",category:"component",description:"Präzisionswerkzeug für Matrixpressung."},{id:"conductor_frame",name:"Leiterrahmen",category:"component",description:"Trägerstruktur für Schaltungen."},{id:"machine_housing",name:"Maschinengehäuse",category:"component",description:"Robustes Gehäuse für Maschinen."},
{id:"red_matrix",name:"Roter Matrix-Baustein",category:"matrix",description:"Basisforschungsbaustein."},{id:"blue_matrix",name:"Blauer Matrix-Baustein",category:"matrix",description:"Fortgeschrittener Forschungsbaustein."},{id:"yellow_matrix",name:"Gelber Matrix-Baustein",category:"matrix",description:"Hochwertiger Forschungsbaustein."},
{id:"energy_cell",name:"Energiezelle",category:"meta",description:"Startressource."},{id:"research_red",name:"Rote Forschungsdaten",category:"meta",description:"Kumulierte rote Forschung."},{id:"research_blue",name:"Blaue Forschungsdaten",category:"meta",description:"Kumulierte blaue Forschung."},{id:"research_points",name:"Forschungspunkte",category:"meta",description:"Punkte für Technologien."}
];
export const RESOURCE_BY_ID = Object.fromEntries(RESOURCES.map(r=>[r.id,r]));
